self_vehicle_properties:
  - vehicle.vehicle_type
  - vehicle.engine_capacity_cc
  - vehicle.propulsion_code
  - vehicle.age_of_vehicle
  - vehicle.vehicle_left_hand_drive
  - vehicle.towing_and_articulation
  - vehicle.journey_purpose_of_driver
  - vehicle.sex_of_driver
  - vehicle.age_of_driver
  - vehicle.vehicle_manoeuvre
other_vehicle_properties:
  - vehicle.vehicle_type
  - vehicle.junction_location
  - vehicle.vehicle_manoeuvre
